apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smartcity-ingress
  namespace: smartcity
  labels:
    app: smartcity
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8081
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
