on:
  push:
    branches: workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code source
        uses: actions/checkout@v6

      - name: Build and test Spring boot
        run: |
          cd  smartcity
          chmod +x mvnw
          ./mvnw clean package
          ./mvnw clean verify
